#应用的包名
name: flutter_app_study

#应用包的描述和简介
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.

#应用的版本号
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

#应用内所依赖的其他包或者插件
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  english_words: ^3.1.0
  provide: ^1.0.0
  http: ^0.12.0+1
  cached_network_image: ^1.1.1
  build_runner: ^1.0.0
  json_serializable: ^2.0.2
  url_launcher: ^5.0.2
  flutter_webview_plugin: ^0.3.1
  sqflite: ^1.1.3
  dio: ^2.1.0
  flutter_swiper: ^1.0.6
  flutter_screenutil: ^0.5.1
  video_player: ^0.10.2+1
  rxdart: ^0.22.4

#开发环境下依赖的工具包【不是flutter本身的依赖】
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.

#flutter的相关配置项
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/3.0x/AppIcon29x29.png
    - assets/2.0x/AppIcon40x40.png

    - assets/2.0x/bg_register.png
    - assets/3.0x/bg_register.png

    - assets/2.0x/tag_tel.png
    - assets/3.0x/tag_tel.png

    - assets/2.0x/tag_u_mail.png
    - assets/3.0x/tag_u_mail.png

    - assets/2.0x/ar_down.png
    - assets/3.0x/ar_down.png

    - assets/2.0x/bg_line.png
    - assets/3.0x/bg_line.png

    - assets/icon_credit_consumption.png
    - assets/icon_credit_dining.png
    - assets/icon_credit_ious.png
    - assets/icon_credit_life.png
    - assets/icon_credit_mall.png
    - assets/icon_credit_trip.png
    - assets/img_allow.png

    - assets/icon_home_evection.png
    - assets/icon_home_lease.png
    - assets/icon_home_recharge.png
    - assets/icon_home_more.png
    - assets/icon_home_remuneration.png
    - assets/icon_home_salary_sign.png
    - assets/icon_home_search.png
    - assets/icon_home_store.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages

  #加载.ttf的矢量图标
  fonts:
      #先定义.ttf矢量图标文件在flutter中的名称
    - family: AppIconFonts
      #引入这个.ttf文件在flutter工程中的绝对路径
      fonts:
          - asset: assets/fonts/iconfont.ttf
